#! /bin/bash

export VERSION="1"
export SYSTEM_DESC="ChimeraOS Zero"
export SYSTEM_NAME="chimeraos-zero"
export USERNAME="gamer"
export SIZE="5000MB"
export ARCHIVE_DATE=$(date -d 'yesterday' +%Y/%m/%d)
export WEBSITE="https://chimeraos.org"
export DOCUMENTATION_URL="https://chimeraos.org/about"
export BUG_REPORT_URL="https://github.com/ChimeraOS/chimeraos/issues"

export KERNEL_PACKAGE="linux"

export PACKAGES="\
	accountsservice \
	gamescope \
	htop \
	inputplumber \
	less \
	lightdm \
	nvidia-open-dkms \
	nvidia-utils \
	pipewire-pulse \
	sudo \
	vim \
	vulkan-intel \
	vulkan-mesa-layers \
	vulkan-radeon \
	wireplumber \
"

export AUR_PACKAGES="\
	downgrade \
	frzr \
	pikaur \
"

export SERVICES="\
	fstrim.timer \
	inputplumber \
	lightdm \
"

export FILES_TO_DELETE="\
	/boot/initramfs-linux-fallback.img \
	/usr/share/SFML \
	/usr/share/doc \
	/usr/share/gtk-doc \
	/usr/share/help \
	/usr/share/man \
"

postinstallhook() {
	# Add sudo permissions
	sed -i '/%wheel ALL=(ALL:ALL) ALL/s/^# //g' /etc/sudoers

	# Disable SPDIF/IEC958 audio output
	sudo sed -e '/\[Mapping iec958/,+5 s/^/#/' -i '/usr/share/alsa-card-profile/mixer/profile-sets/default.conf'
}
