#! /bin/bash

export VERSION="1"
export SYSTEM_DESC="kazeta"
export SYSTEM_NAME="kazeta"
export USERNAME="gamer"
export SIZE="5000MB"
export ARCHIVE_DATE=$(date -d 'yesterday' +%Y/%m/%d)
export WEBSITE="https://kazeta.org"
export DOCUMENTATION_URL="https://kazeta.org"
export BUG_REPORT_URL="https://github.com/kazetaos/kazeta/issues"

export KERNEL_PACKAGE="linux"

export PACKAGES="\
	accountsservice \
	fuse2 \
	fuse3 \
	gamescope \
	htop \
	inputplumber \
	less \
	lightdm \
	linux-firmware \
	nvidia-open \
	nvidia-utils \
	pipewire-jack \
	pipewire-pulse \
	sudo \
	vim \
	vulkan-intel \
	vulkan-mesa-layers \
	vulkan-radeon \
	wireplumber \
"

export AUR_PACKAGES="\
	downgrade \
	frzr \
	pikaur \
"

export SERVICES="\
	fstrim.timer \
	inputplumber \
	lightdm \
"

export FILES_TO_DELETE="\
	/boot/initramfs-linux-fallback.img \
	/usr/share/SFML \
	/usr/share/doc \
	/usr/share/gtk-doc \
	/usr/share/help \
	/usr/share/man \
"

postinstallhook() {
	# Add sudo permissions
	sed -i '/%wheel ALL=(ALL:ALL) ALL/s/^# //g' /etc/sudoers

	# Disable SPDIF/IEC958 audio output
	sed -e '/\[Mapping iec958/,+5 s/^/#/' -i '/usr/share/alsa-card-profile/mixer/profile-sets/default.conf'

	# Set a default timezone, FNA/XNA (and probably others) need it
	ln -s /usr/share/zoneinfo/UTC /etc/localtime

	mkdir -p /home/${USERNAME}/.local/share
	ln -s /var/kazeta /home/${USERNAME}/.local/share/kazeta
}
