name: System image build

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

on:
  workflow_dispatch:

jobs:
  build-docker-image:
    name: Build and publish docker container
    uses: ./.github/workflows/build-builder.yml

  list-pkgbuilds:
    name: List Packages
    runs-on: ubuntu-latest
    outputs:
      aur-pkgs: ${{ steps.set-aur-pkgs.outputs.matrix }}
      pkgs: ${{ steps.set-pkgs.outputs.matrix }}
    steps:
      - uses: actions/checkout@v4
      - id: set-aur-pkgs
        run: source ./manifest ; echo "matrix=$(echo ${AUR_PACKAGES} | jq -R -s -c 'split(" ")')" >> $GITHUB_OUTPUT
        shell: bash
      - id: set-pkgs
        run: echo "matrix=$(ls -d pkgs/*/ | jq -R -s -c 'split("\n")[:-1]')" >> $GITHUB_OUTPUT
        shell: bash

  aur-pkgbuild:
    needs:
     - build-docker-image
     - list-pkgbuilds
    name: Build AUR package
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        package: ${{ fromJson(needs.list-pkgbuilds.outputs.aur-pkgs) }}
    steps:
      - uses: actions/checkout@v4
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
      - name: Build packages
        run: |
          docker pull ${{ steps.meta.outputs.tags }}
          docker run --rm -v $(pwd):/workdir --entrypoint=/workdir/aur-pkgs/build-aur-package.sh ${{ steps.meta.outputs.tags }} ${{ matrix.package }}
      - name: Upload Package Archives
        uses: actions/upload-artifact@v4
        with:
            name: AUR-packages-${{ matrix.package }}
            path: aur-pkgs/*.pkg.tar*

  build:
    needs:
     - build-docker-image
     - aur-pkgbuild
    name: Build OS UNSTABLE image
    uses: ./.github/workflows/build-system-image.yml
    with:
      postfix: "[UNSTABLE]"

  build-iso:
    name: Build Installer ISO
    needs: build # This job will only start after the main system image is built
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Installer Repository
        uses: actions/checkout@v4
        with:
          repository: kazetaos/install-media # Checks out the installer repo
          path: install-media

      - name: Download System Image Artifact
        uses: actions/download-artifact@v4
        with:
          name: kazeta-plus-image # The name of the artifact from the 'build' job
          path: install-media/installer/airootfs/root/

      - name: Run the ISO Build Script
        run: |
          cd install-media
          sudo ./build-iso-docker.sh

      - name: Upload Installer ISO Artifact
        uses: actions/upload-artifact@v4
        with:
          name: kazeta-plus-iso
          path: install-media/out/*.iso
